name: "[PR] Build open-api-spec"

on:
  workflow_call:
    inputs:
      COMMAND:
        required: false
        type: string
        default: 'generate:spec'
      FILE_PATH:
        required: false
        type: string
        default: 'postman/schemas/index.json'
      BUMP_PROJECT_NAME:
        required: false
        type: string
      BUMP_HUB_ID:
        required: false
        type: string
      DEPLOY_BUMP_SPEC:
        required: false
        type: boolean
    secrets:
      token:
        required: true
      VERDACCIO_FORTO_IO_TOKEN:
        required: true
      BUMP_TOKEN:
        required: false

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  build-spec:
    name: Build Open API specification
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn ${{ inputs.COMMAND }}
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: ${{ inputs.FILE_PATH }}
      - name: commit-open-api-spec
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'updated open-api specification'
          commit_options: '--no-verify'
          file_pattern: ${{ inputs.FILE_PATH }}
        if: env.GIT_DIFF
      - name: install bump
        run: npm install bump-cli
        if: inputs.DEPLOY_BUMP_SPEC
      - name: deploy openAPI specifiction from file
        run: npm exec -- bump deploy ${{ inputs.FILE_PATH }} -d ${{ inputs.PROJECT_NAME }} -t ${{ secrets.BUMP_TOKEN }} --hub ${{ inputs.BUMP_HUB_ID }} --auto-create
        if: inputs.DEPLOY_BUMP_SPEC
