name: "[PR] Build open-api-spec"

on:
  workflow_call:
    inputs:
      COMMAND:
        required: false
        type: string
        default: 'generate:spec'
      FILE_PATH:
        required: false
        type: string
        default: 'postman/schemas/index.json'
    secrets:
      token:
        required: true
      VERDACCIO_FORTO_IO_TOKEN:
        required: true

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  build-spec:
    name: Build Open API specification
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn ${{ inputs.COMMAND }}
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: ${{ inputs.FILE_PATH }}
      - name: commit-open-api-spec
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'updated open-api specification'
          commit_options: '--no-verify'
          file_pattern: ${{ inputs.FILE_PATH }}
        if: env.GIT_DIFF

