name: "[PR] Build open-api-spec"

on:
  workflow_call:
    inputs:
      COMMAND:
        required: false
        type: string
        default: 'generate:spec'
      FILE_PATH:
        required: false
        type: string
        default: 'postman/schemas/index.json'
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'
    secrets:
      token:
        required: false

jobs:
  build-spec:
    name: Build Open API specification
    runs-on: ubuntu-22.04
    steps:
      # Authenticate to Github via Token Factory
      - name: Fetch Github App token
        id: github-auth
        uses: freight-hub/get-github-token-action@v1
        with:
          contents: write
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.github-auth.outputs.token }}
      - name: 'Authenticate to Google Cloud'
        id: 'gcloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          token_format: access_token
          access_token_lifetime: '600s'
          create_credentials_file: false
      - name: 'Export FORTO_ARTIFACTS_TOKEN variable'
        run: echo "FORTO_ARTIFACTS_TOKEN=${{ steps.gcloud.outputs.access_token }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn ${{ inputs.COMMAND }}
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: ${{ inputs.FILE_PATH }}
      - name: commit-open-api-spec
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'updated open-api specification'
          commit_options: '--no-verify'
          file_pattern: ${{ inputs.FILE_PATH }}
        if: env.GIT_DIFF
