name: "[PR] Build open-api-spec"

on:
  workflow_call:
    inputs:
      COMMAND:
        required: false
        type: string
        default: 'generate:spec'
      FILE_PATH:
        required: false
        type: string
        default: 'postman/schemas/index.json'
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'
    secrets:
      token:
        required: true

jobs:
  build-spec:
    name: Build Open API specification
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: '600s'
      - name: 'Update .npmrc with new token'
        run: echo "FORTO_ARTIFACTS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn ${{ inputs.COMMAND }}
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: ${{ inputs.FILE_PATH }}
      - name: commit-open-api-spec
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'updated open-api specification'
          commit_options: '--no-verify'
          file_pattern: ${{ inputs.FILE_PATH }}
        if: env.GIT_DIFF