name: "[PR] Build, lint and test (Localstack and PubSub)"

on:
  workflow_call:
    inputs:
      LOCALSTACK_IMAGE_TAG:
        description: 'Localstack version to use'
        required: false
        type: string
        default: 'latest'
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'

jobs:
  build-lint-test:
    name: Build - Lint Check - Test
    runs-on: ubuntu-22.04
    services:
      localstack:
        image: localstack/localstack:${{ inputs.LOCALSTACK_IMAGE_TAG }}
        ports:
          - 4566-4597:4566-4597
        env:
          AWS_DEFAULT_REGION: eu-west-1
          EDGE_PORT: 4566
          SERVICES: sqs,sns
      pubsub:
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:316.0.0-emulators
        ports:
          - "8085:8085"
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: '600s'
      - name: 'Update .npmrc with new token'
        run: echo "FORTO_ARTIFACTS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - name: Install gcloud PubSub Emulator
        uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'beta,pubsub-emulator'
      - name: 'Start Pub/Sub emulator'
        run: |
          gcloud beta emulators pubsub start --project test-project --host-port 0.0.0.0:8085 &
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/
          /usr/local/bin/aws --version
      - run: yarn test --ci --coverage
        env:
          AWS_SECRET_ACCESS_KEY: 'ignore_me'
          AWS_ACCESS_KEY_ID: 'ignore_me'
