name: "[PR] Build, lint and test"

on:
  workflow_call

jobs:
  build-lint-test:
    name: Build - Lint Check - Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Call Authentication Workflow'
        uses: freight-hub/gh-workflows/.github/workflows/npm-auth.yml@main
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - run: yarn test --ci --coverage
