name: "[PR] Build, lint and test (Localstack and PubSub)"

on:
  workflow_call:
    secrets:
      VERDACCIO_FORTO_IO_TOKEN:
        required: true
    inputs:
      LOCALSTACK_VERSION:
        description: 'Localstack version to use'
        required: false
        type: string
        default: 'latest'

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  build-lint-test:
    name: Build - Lint Check - Test
    runs-on: ubuntu-22.04
    services:
      localstack:
        image: localstack/localstack:${{ inputs.LOCALSTACK_VERSION }}
        ports:
          - 4566-4597:4566-4597
        env:
          AWS_DEFAULT_REGION: eu-west-1
          EDGE_PORT: 4566
          SERVICES: sqs,sns
      pubsub:
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:316.0.0-emulators
        ports:
          - "8085:8085"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - name: Install gcloud PubSub Emulator
        uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'beta,pubsub-emulator'
      - name: 'Start Pub/Sub emulator'
        run: |
          gcloud beta emulators pubsub start --project test-project --host-port 0.0.0.0:8085 &
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/
          /usr/local/bin/aws --version
      - run: yarn test --ci --coverage
        env:
          AWS_SECRET_ACCESS_KEY: 'ignore_me'
          AWS_ACCESS_KEY_ID: 'ignore_me'
