name: "[PR] Build, lint and test"

on:
  workflow_call:
    inputs:
      COMMAND:
        required: false
        type: string
        default: 'test --ci --coverage'
      TEST_ENVIRONMENT:
        required: false
        type: string
        default: 'test'
      TEST_TYPE:
        required: false
        type: choice
        default: 'unit'
        options:
          - unit
          - integration
    secrets:
      VERDACCIO_FORTO_IO_TOKEN:
        required: true

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  build-lint-test:
    name: Build - Lint Check - Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - run: yarn ${{ inputs.COMMAND }}
        env:
          NODE_ENV: ${{ inputs.TEST_ENVIRONMENT }}
          JEST_JUNIT_OUTPUT: "coverage/junit/junit.xml"
      # If the branch is main, overwrite the main-coverage file
      - name: Upload coverage report artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage/${{ inputs.TEST_TYPE }}/coverage-summary.json
          overwrite: true


