name: "[PR] Build, lint and test (Localstack)"

on:
  workflow_call

jobs:
  build-lint-test:
    name: Build - Lint Check - Test
    runs-on: ubuntu-22.04
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566-4597:4566-4597
        env:
          AWS_DEFAULT_REGION: eu-west-1
          EDGE_PORT: 4566
          SERVICES: sqs,sns
    steps:
      - uses: actions/checkout@v3
      - name: 'Call Authentication Workflow'
        uses: freight-hub/gh-workflows/.github/workflows/npm-auth.yml@main
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/
          /usr/local/bin/aws --version
      - run: yarn test --ci --coverage
        env:
          AWS_SECRET_ACCESS_KEY: 'ignore_me'
          AWS_ACCESS_KEY_ID: 'ignore_me'
