name: "[PR] Build, lint and test"

on:
  workflow_call:
    inputs:
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'

jobs:
  build-lint-test:
    name: Build - Lint Check - Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        id: 'gcloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          token_format: access_token
          access_token_lifetime: '600s'
          create_credentials_file: false
      - name: 'Export FORTO_ARTIFACTS_TOKEN variable'
        run: echo "FORTO_ARTIFACTS_TOKEN=${{ steps.gcloud.outputs.access_token }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - run: yarn test --ci --coverage
