name: "Authenticate to Google Cloud"

on:
  workflow_call:
    inputs:
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'

jobs:
  authenticate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: '600s'
      - name: 'Update .npmrc with new token'
        run: echo "FORTO_ARTIFACTS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV