# This workflow will trigger, but only add the status check after the CI check has run
name: "[PR] Build, check and publish"

on:
  workflow_call:

jobs:
  pre-release:
    # This name needs to match the name in build-check-publish
    name: Publish pre-release version
    runs-on: ubuntu-latest
    # Commit message must be same as `package-build-check-publish.yml`
    if: github.event.head_commit.message == '[BUMP] Update package.json to next stable version'
    steps:
      - run: 'echo "No build required"'
