name: "[Main] Build, check and publish"

on:
  workflow_call:
    secrets:
      VERDACCIO_FORTO_IO_TOKEN:
        required: true

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  publish-main:
    name: Publish main version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish
      - name: get-npm-version
        uses: jaywcjlove/github-action-package@main
        id: package-info
      - name: create-release
        uses: freight-hub/action-create-release@v1.1
        with:
          tag: ${{ steps.package-info.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

