name: "[PR] Build, check and publish"

on:
  workflow_call:
    secrets:
      token:
        required: false
    inputs:
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'
      publish-to-gar:
        description: 'Boolean flag to control publishing flow'
        required: false
        default: true
        type: boolean
      gar-registry:
        description: 'The registry to publish to'
        required: false
        default: npm-internal-canary
        type: string

jobs:
  pre-release:
    name: Publish pre-release version
    runs-on: ubuntu-22.04
    steps:
      # Authenticate to Google Cloud
      - name: 'Authenticate to Google Cloud'
        id: 'gcloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          token_format: access_token
          access_token_lifetime: '600s'
          create_credentials_file: false
      - name: 'Export FORTO_ARTIFACTS_TOKEN variable'
        run: echo "FORTO_ARTIFACTS_TOKEN=${{ steps.gcloud.outputs.access_token }}" >> $GITHUB_ENV
      # Authenticate to Github via Token Factory
      - name: Fetch Github App token
        id: github-auth
        uses: freight-hub/get-github-token-action@v1
        with:
          contents: write
          pull-requests: write
      # Set up the repo
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.github-auth.outputs.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      # Detect versioning
      - name: bump-version-from-tag
        id: tag
        uses: freight-hub/action-tag-bump-version@v1.4
        with:
          build_number: ${{ github.run_number }}
          token: ${{ steps.github-auth.outputs.token }}
          fallback_tag: 0.0.1
      # Set the new_version on package.json
      - run: yarn version --new-version ${{ steps.tag.outputs.new_version }} --no-git-tag-version
      - name: commit-stable-version-change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update package.json to next stable version'
          file_pattern: package.json
      # Prepare for a versioned release
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn version --new-version ${{ steps.tag.outputs.pre_release_version }} --no-git-tag-version
      # Publish a canary release
      - name: Publish and tag on NPM repository
        run: |
          rm -f ~/.npmrc .npmrc .yarnrc
          echo "//europe-west1-npm.pkg.dev/forto-artifacts/${{ inputs.gar-registry }}/:_authToken=\${FORTO_ARTIFACTS_TOKEN}" >> .npmrc
          yarn publish --registry https://europe-west1-npm.pkg.dev/forto-artifacts/${{ inputs.gar-registry }}/ --tag canary
