name: "[Main] Build, check and publish"

on:
  workflow_call:
    secrets:
      VERDACCIO_FORTO_IO_TOKEN:
        required: true
      SLACK_PACKAGE_WEBHOOK_URL:
        required: true

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  publish-main:
    name: Publish main version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish
      - name: get-npm-version
        uses: jaywcjlove/github-action-package@main
        id: package-info
      - name: create-release
        uses: freight-hub/action-create-release@v1.1
        permissions:
            contents: write
        with:
          tag: ${{ steps.package-info.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify slack
        id: slack
        uses: freight-hub/action-slack-notify@v1.1
        permissions:
            contents: write
        with:
          slack_webhook_url: ${{ secrets.SLACK_PACKAGE_WEBHOOK_URL }}
          message: ${{ steps.package-info.outputs.name }}:${{ steps.package-info.outputs.version }} was released!
          is_markdown: false

