name: "[Main] Build, check and publish"

on:
  workflow_call:
    inputs:
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'
      publish-to-gar:
        description: 'Boolean flag to control publishing'
        required: false
        default: true
        type: boolean
      gar-registry:
        description: 'The registry to publish to'
        required: false
        default: npm-internal-release
        type: string
    secrets:
      VERDACCIO_FORTO_IO_TOKEN:
        required: true
      SLACK_PACKAGE_WEBHOOK_URL:
        required: true

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  publish-main:
    name: Publish main version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: '600s'
      - name: 'Update .npmrc with new token'
        run: echo "FORTO_ARTIFACTS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Publish to npm
        if: ${{ inputs.publish-to-gar }}
        run: |
          rm -f ~/.npmrc .npmrc .yarnrc
          echo "always-auth=true" >> ~/.npmrc
          echo "//europe-west1-npm.pkg.dev/forto-artifacts/${{ inputs.gar-registry }}/:_authToken=${FORTO_ARTIFACTS_TOKEN}" >> ~/.npmrc
          npm publish --registry https://europe-west1-npm.pkg.dev/forto-artifacts/${{ inputs.gar-registry }}
      - if: ${{ !inputs.publish-to-gar }}
        run: |
          rm -f ~/.npmrc .npmrc .yarnrc
          echo -e "always-auth=true\n//verdaccio.forto.io/:_authToken=\${VERDACCIO_FORTO_IO_TOKEN}\nregistry=https://verdaccio.forto.io" >> ~/.npmrc
          yarn publish --registry https://verdaccio.forto.io
      - name: get-npm-version
        uses: jaywcjlove/github-action-package@main
        id: package-info
      - name: create-release
        uses: freight-hub/action-create-release@v1.1
        with:
          tag: ${{ steps.package-info.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify slack
        id: slack
        uses: freight-hub/action-slack-notify@v1.1
        with:
          slack_webhook_url: ${{ secrets.SLACK_PACKAGE_WEBHOOK_URL }}
          message: ${{ steps.package-info.outputs.name }}:${{ steps.package-info.outputs.version }} was released!
          is_markdown: false

