name: "[Main] Build, check and publish"

on:
  workflow_call:
    secrets:
      VERDACCIO_FORTO_IO_TOKEN:
        required: true
      SLACK_WEBHOOK:
        required: true

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  publish-main:
    name: Publish main version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish
      - name: get-npm-version
        uses: jaywcjlove/github-action-package@main
        id: package-info
      - name: create-release
        uses: freight-hub/action-create-release@v1.1
        with:
          tag: ${{ steps.package-info.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: package-releases
          SLACK_COLOR: good
          SLACK_ICON: https://github.com/freight-hub.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: ${{ steps.package-info.outputs.name }}:${{ steps.package-info.outputs.version }} published!
          SLACK_USERNAME: forto-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

