name: "[PR] Build, check and publish"

on:
  workflow_call:
    secrets:
      VERDACCIO_FORTO_IO_TOKEN:
        required: false
      token:
        required: true
    inputs:
      service_account:
        description: 'Google Cloud service account'
        type: string
        required: false
        default: 'gha-workflow@forto-workload-identity.iam.gserviceaccount.com'
      publish-to-gar:
        description: 'Boolean flag to control publishing flow'
        required: false
        default: true
        type: boolean
      gar-registry:
        description: 'The registry to publish to'
        required: false
        default: npm-internal-canary
        type: string

env:
  VERDACCIO_FORTO_IO_TOKEN: ${{ secrets.VERDACCIO_FORTO_IO_TOKEN }}

jobs:
  pre-release:
    name: Publish pre-release version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/630000710192/locations/global/workloadIdentityPools/github/providers/actions-token
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: '600s'
      - name: 'Update .npmrc with new token'
        run: echo "FORTO_ARTIFACTS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: bump-version-from-tag
        id: tag
        uses: freight-hub/action-tag-bump-version@v1.4
        with:
          build_number: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fallback_tag: 0.0.1
      # set the new_version on package.json
      - run: yarn version --new-version ${{ steps.tag.outputs.new_version }} --no-git-tag-version
      - name: commit-stable-version-change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update package.json to next stable version'
          file_pattern: package.json
      # set the publish the release version
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn version --new-version ${{ steps.tag.outputs.pre_release_version }} --no-git-tag-version
      - name: Publish to tag & npm
        if: ${{ inputs.publish-to-gar }}
        run: |
          rm -f ~/.npmrc .npmrc .yarnrc
          echo "FORTO_ARTIFACTS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
          echo "//europe-west1-npm.pkg.dev/forto-artifacts/${{ inputs.gar-registry }}/:_authToken=${FORTO_ARTIFACTS_TOKEN}" >> .npmrc
          yarn publish --registry https://europe-west1-npm.pkg.dev/forto-artifacts/${{ inputs.gar-registry }}/ --tag canary
      - if: ${{ !inputs.publish-to-gar }}
        run: |
          rm -f ~/.npmrc .npmrc .yarnrc
          echo -e "always-auth=true\n//verdaccio.forto.io/:_authToken=\${VERDACCIO_FORTO_IO_TOKEN}\nregistry=https://verdaccio.forto.io" >> ~/.npmrc
          yarn publish --registry https://verdaccio.forto.io --tag ${{ steps.tag.outputs.pre_release_version }}
